Rails.application.routes.draw do
  resources 'user'
  resources 'posts'
  resources 'friend_request'
  get 'user/index'
  root 'user#index'
  get '/login', to: 'session#new'
  get '/signup', to: 'user#signup'
  get '/profile', to: 'user#profile'
  get '/users/search', to: 'user#search'
  get '/users/show', to: 'user#users'
  post '/signup', to: 'user#create'
  post '/login', to: 'session#create'
  post '/friend_request/accept', to: 'friend_request#accept'
  delete '/logout', to: 'session#destroy'
  delete '/user/delete', 'user#destroy'
  delete 'friend_request/delete', to: 'friend_request#destroy'
end
